app/support/urls.py
from django.urls import path
from .views import (FAQView, FAQListView, AssistanceView, AssistanceCreateView,AssistanceListView, 
                    AssistanceUpdateView, FeedbackView)

app_name="support"

urlpatterns = [
    
    path('faq/', FAQView.as_view(), name="faq"),
    path('faq_list/', FAQListView.as_view(), name="faq_list"),
    path('assistance/', AssistanceView.as_view(), name="assistance"),
    path('assistance_list/', AssistanceListView.as_view(), name="assistance_list"),
    path('assistance_create/', AssistanceCreateView.as_view(), name="assistance_create"),
    path('assistance_update/<int:pk>', AssistanceUpdateView.as_view(), name="assistance_update"),
    path('feedback/', FeedbackView.as_view(), name="feedback"),#AJAX
    
    ]

curriculo/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from home.views import Error404View, Error500View


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('account.urls')),
    path('profile/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('support/', include('app.support.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    
handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

home/urls.py
from django.urls import path
from .views import HomeView

app_name="home"


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    
    ]

app/support/models.py
from django.db import models
from django.contrib.auth.models import User


class FAQModel(models.Model):
    "FAQ Model"
    
    id=models.AutoField(primary_key=True)
    question=models.CharField(max_length=100)
    answer=models.TextField(max_length=500)
    image=models.ImageField(upload_to='PF/%y/%m/%d', null=True, blank=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)


class AssistanceModel(models.Model):
    "Assistance/support Model"
    
    id=models.AutoField(primary_key=True)
    issue=models.CharField(max_length=40)
    description=models.TextField(max_length=500)
    status=models.BooleanField(default=True)#Activo o cerrado
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

class FeedbackModel(models.Model):
    "Feedback model"
    
    id=models.AutoField(primary_key=True)
    issue=models.CharField(max_length=40)
    description=models.TextField(max_length=500)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

app/support/forms.py
from django import forms
from .models import AssistanceModel, FeedbackModel


class AssistanceForm(forms.ModelForm):
    "Assitance Form"

    class Meta:
        model=AssistanceModel
        fields="__all__"
        exclude=['status']

        labels={
        "issue":"Asunto",
        "description":"Descripción",
        }

class FeedbackForm(forms.ModelForm):
    "Feedback form"
    
    class Meta:
        model=FeedbackModel
        fields="__all__"
        exclude=['user']
        labels={
        "issue":"Asunto",
        "description":"Descripción"
        }

app/support/views.py
import json
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.core.serializers import serialize
from django.views.generic import TemplateView, ListView, CreateView
from django.urls import reverse_lazy
from django.views.generic.base import View
from django.views.generic.edit import UpdateView
from app.support.models import FAQModel, AssistanceModel, FeedbackModel
from app.support.forms import AssistanceForm, FeedbackForm


class FAQView(TemplateView):
    """Template:FAQ
        
        
        :TemplateView: django view
    """

    template_name="support/faq.html"

class FAQListView(ListView):
    """FAQ
        Ajax request
        
        :ListView: django view
    """

    model=FAQModel
    queryset=model.objects.all()

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            data=serialize("json", self.queryset)
            return HttpResponse(data, "application/json")
        
        else:    
            return redirect("support:faq")


class AssistanceView(TemplateView):
    "Support template"
    
    template_name="support/assistance/assistance.html"


class AssistanceListView(ListView):
    "Support List"
    
    model=AssistanceModel
    template_name="support/assistance/list.html"
    context_object_name="assistance"

class AssistanceCreateView(CreateView):
    "Create support"

    model=AssistanceModel
    form_class=AssistanceForm
    template_name="support/assistance/create.html"
    context_object_name="form"
    success_url=reverse_lazy("support:assistance")

class AssistanceUpdateView(UpdateView):
    """Update support
    
    
        :UpdateView: django view
    """

    model=AssistanceModel
    form_class=AssistanceForm
    template_name="support/assistance/update.html"
    context_object_name="form"
    success_url=reverse_lazy("support:assistance_list")

class FeedbackView(CreateView):
    """Feedback view
        Ajax request
        
        
        :CreateViewm: django view
    """
    
    model=FeedbackModel
    form_class=FeedbackForm
    template_name="support/feedback/index.html"
    context_object_name="form"
    
    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form=self.form_class(data=request.POST)
            if form.is_valid():
                feedback=FeedbackModel(
                        issue=form.cleaned_data.get("issue"),
                        description=form.cleaned_data.get("description"),
                        user=request.user
                )
                feedback.save()
                
                message="se registro correctamente "
                error="No hay error"
                response=JsonResponse({'mensaje':message, "error":error})
                response.status_code=201
                return response
            else:
                message="no se registro correctamente"
                error=form.errors
                response=JsonResponse({'mensaje':message, "error":error})
                response.status_code=400
                return response
        else:
            return redirect("support:feedback")
    
    
    

templates/support/assistance/assistance.html
{% extends "dashboard/index.html" %}
{% load static %}
{% block right-content %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h2>Diseño Personalizado</h2>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">
        <div class="row">      
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Asesoría solicitada</strong>
                    </div>
                    <button class="btn btn-primary" onclick="open_modal_create('{% url 'support:assistance_create' %}')">Solicitar Asesoría</button>
                    <a class="btn btn-success" href="{% url 'support:assistance_list' %}">Lista de asesoria</a>
                </div>              
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="create" role="dialog"></div>
<div class="clearfix"></div>
{% endblock %}
{% block scripts %}
<script text="text/javascript">
    var $=jQuery.noConflict();
    function open_modal_create(url){
        $('#create').load(url, function(){
            $(this).modal('show');
        })
        
    }
</script>
{% endblock scripts %}

templates/support/assistance/create.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Crear solicitud</h2>
            <button class="close" type="button" data-dismiss="modal" aria-Label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'support:assistance_create' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="modal-body">
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary" type="submit" >Enviar</button>
            </div>
        </form>
    </div>
</div>

templates/support/assistance/list.html
{% extends "dashboard/index.html" %}
{% load static %}
{% block right-content %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h2>Diseño Personalizado</h2>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">
        <div class="row">      
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Lista</strong>
                    </div>
                    {% for ast in assistance %}
                        <p>{{ast.id}}</p>
                        <p>{{ast.issue}}</p>
                        <p>{{ast.description}}</p>
                        <button class="btn btn-primary" onclick="open_modal_update('{% url 'support:assistance_update' ast.id %}')">Editar</button>
                    {% endfor %}
                </div>              
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="update" role="dialog"></div>
<div class="clearfix"></div>
{% endblock %}
{% block scripts %}
<script text="text/javascript">
    var $=jQuery.noConflict();
    function open_modal_update(url){
        $('#update').load(url, function(){
            $(this).modal('show');
        })   
    }
</script>
{% endblock scripts %}

templates/support/assistance/update.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Crear solicitud</h2>
            <button class="close" type="button" data-dismiss="modal" aria-Label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'support:assistance_update' object.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="modal-body">
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary" type="submit" >Enviar</button>
            </div>
        </form>
    </div>
</div>