curriculo/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from home.views import Error404View, Error500View


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('account.urls')),
    path('profile/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('support/', include('app.support.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    
handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import( DashboardView, DatosPersonalesCreateView, DatosPersonalesView, DatosPersonalesUpdateView, 
                    DatosContactoView,DatosContactoCreateView, DatosContactoUpdateView, ExperienciaProfesionalView,
                    ExperienciaProfesionalUpdateView,ExperienciaProfesionalCreateView,ExperienciaProfesionaDeleteView, 
                    ObjetivosView, ObjetivosCreateView, ObjetivosUpdateView, FormacionAcademicaView, 
                    FormacionAcademicaCreateView, FormacionAcademicaUpdateView, FormacionAcademicaDeleteView,
                    IdiomasView, IdiomasCreateView, IdiomasUpdateView, IdiomasDeleteView,CursosView, CursosCreateView,
                    CursosUpdateView, CursosDeleteView, CvFileView )


urlpatterns = [
    path('', login_required(DashboardView.as_view()), name="dashboard"),
    path('datos_personales/', login_required(DatosPersonalesView.as_view()), name="datos_personales"),
    path('datos_personales_agregar/',login_required(DatosPersonalesCreateView.as_view()), 
                                                name="datos_personales_agregar"),
    path('datos_personales_modificacion/<int:pk>', login_required(DatosPersonalesUpdateView.as_view()), 
                                                name="datos_personales_modificacion"),
    path('datos_contacto/',login_required(DatosContactoView.as_view()), name="datos_contacto"),
    path('datos_contacto_agregar/', login_required(DatosContactoCreateView.as_view()), name="datos_contacto_agregar"),
    path('datos_contacto_modificacion/<int:pk>', login_required(DatosContactoUpdateView.as_view()), 
                                                name="datos_contacto_modificacion"),
    path('objetivos/', login_required(ObjetivosView.as_view()), name="objetivos"),
    path('objetivos_agregar/', login_required(ObjetivosCreateView.as_view()), name="objetivos_agregar"),
    path('objetivos_modificacion/<int:pk>', login_required(ObjetivosUpdateView.as_view()), 
                                                name="objetivos_modificacion"),
    path('experiencia_profesional/', login_required(ExperienciaProfesionalView.as_view()), 
                                                name="experiencia_profesional"),
    path('experiencia_profesional_modificacion/<int:pk>', login_required(ExperienciaProfesionalUpdateView.as_view()), 
                                                name="experiencia_profesional_modificacion"),
    path('experiencia_profesional_agregar/', login_required(ExperienciaProfesionalCreateView.as_view()), 
                                                name="experiencia_profesional_agregar"),    
    path('experiencia_profesional_eliminar/<int:pk>', login_required(ExperienciaProfesionaDeleteView.as_view()), 
                                                name="experiencia_profesional_eliminar"),                                                
    path('formacion_academica/', login_required(FormacionAcademicaView.as_view()), name="formacion_academica"),
    path('formacion_academica_modificacion/<int:pk>', login_required(FormacionAcademicaUpdateView.as_view()), 
                                                name="formacion_academica_modificacion"),
    path('formacion_academica_agregar/',login_required(FormacionAcademicaCreateView.as_view()), 
                                                name="formacion_academica_agregar"),    
    path('formacion_academica_eliminar/<int:pk>', login_required(FormacionAcademicaDeleteView.as_view()), 
                                                name="formacion_academica_eliminar"),                                                                                        
    path('idiomas/', login_required(IdiomasView.as_view()), name="idiomas"),
    path('idiomas_modificacion/<int:pk>', login_required(IdiomasUpdateView.as_view()), name="idiomas_modificacion"),
    path('idiomas_agregar/', login_required(IdiomasCreateView.as_view()), name="idiomas_agregar"),    
    path('idiomas_eliminar/<int:pk>', login_required(IdiomasDeleteView.as_view()), name="idiomas_eliminar"),
    path('cursos/',login_required(CursosView.as_view()), name="cursos"),
    path('cursos_modificacion/<int:pk>', login_required(CursosUpdateView.as_view()), name="cursos_modificacion"),
    path('cursos_agregar/', login_required(CursosCreateView.as_view()), name="cursos_agregar"),    
    path('cursos_eliminar/<int:pk>', login_required(CursosDeleteView.as_view()), name="cursos_eliminar"),
    path('cv', login_required(CvFileView.as_view()), name="cv"),
]

home/urls.py
from django.urls import path
from .views import HomeView

app_name="home"


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    
    ]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

def user_directory_path(instance, filename):
    "Photo path"
    
    return 'photo/user_{0}/{1}'.format(instance.user.id, filename)


class DatosPersonalesModel(models.Model):
    
    sex_op=(
        ('Femenino', 'Mujer'),
        ('Masculino', 'Hombre'),
        ('NA', 'No definido'),
    )

    relocate_op=(
        ('Si', 'Reubicarse'),
        ('No', 'No reubicarse'),
    
    )

    id=models.BigAutoField("id", primary_key=True,)
    date_of_birth=models.DateField("date_of_birt", blank=True, null=True)
    image=models.ImageField("image", upload_to=user_directory_path, blank=True, null=True)#upload_to='photo/%y/%m/%d/'
    sex=models.CharField("sex", max_length=12, choices=sex_op, blank=True, null=True)
    relocate=models.CharField('relocate', max_length=2, choices=relocate_op, help_text="Dispuesto a reubicarse")
    country=models.CharField("country", max_length=30, blank=True, null=True)
    zip_code=models.IntegerField("zip_code", blank=True, null=True)
    state=models.CharField(max_length=50,blank=True, null=True)
    city=models.CharField(max_length=50,blank=True, null=True)
    town=models.CharField(max_length=50,blank=True, null=True)
    other=models.TextField(max_length=200, blank=True, null=True, help_text="Otra información, opcional")
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="user")

    class Meta:
        ordering = ["id"]
        verbose_name = "Dato Personal"    
        verbose_name = "Dato Personales"    
    
    def __str__(self):
        return self.city

    def userStatus(self):
        "Retorna si nacio el siglo XX o XXI"
        import datetime
        if self.date_of_birth < datetime.date(1999, 12,31):
            return ("Siglo XX")
        else:
            return "Siglo XXI"


class DatosContactoModel(models.Model):
    
    id=models.AutoField(primary_key=True)
    telephone=models.IntegerField(blank=True, null=True)
    cellphone=models.IntegerField(blank=True, null=True)
    linkedin_social_url=models.URLField(max_length=70, blank=True, default="https://curriculo.page")
    github_social_url=models.URLField(max_length=70, blank=True, default="https://curriculo.page")
    facebook_social_url=models.URLField(max_length=70, blank=True,default="https://curriculo.page")
    twitter_social_url=models.URLField(max_length=70, blank=True, default="https://curriculo.page")
    instagram_social_url=models.URLField(max_length=70, blank=True,default="https://curriculo.page")
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Datos de Contacto"
        ordering = ["id"]

    def __str__(self):
        return str(self.cellphone)


class ObjetivoProfesionalModel(models.Model):
    
    list_divisa=(
        ("MX", "MX"),
        ("USD", "USD"),
    )
    
    id=models.AutoField(primary_key=True)
    employment=models.CharField(max_length=50)
    salary=models.FloatField()
    divisa=models.CharField(max_length=5, choices=list_divisa, blank=True, null=True)
    objective=models.TextField(max_length=200, blank=True, null=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name="Objetivo"
        verbose_name_plural = "Objetivos"
        ordering = ["id"]

    def __str__(self):
        return self.employment

class ExperienciaProfesionalModel(models.Model):
    
    id=models.AutoField(primary_key=True)
    employment=models.CharField(max_length=50, blank=False)
    company=models.CharField(max_length=70,  blank=False)
    activities=models.TextField(max_length=200)
    start_date=models.DateField(blank=False)
    departure_date=models.DateField(blank=True, null=True)
    is_active=models.BooleanField(default=False, blank=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Experiencia profesional"
        ordering = ["id"]

    def __str__(self):
        return self.employment

class FormacionAcademicaModel(models.Model):
    
    leve_list=(
        ('Primaria','Primaria'),
        ('Secundaria','Secundaria'),
        ('Preparatoria','Preparatoria'),
        ('Licenciatura','Licenciatura'),
        ('Posgrado','Posgrado'),
    )
    id=models.AutoField(primary_key=True)
    educational_level=models.CharField(choices=leve_list, max_length=18, blank=False)
    college=models.CharField(max_length=70, blank=False)
    career=models.CharField(max_length=50, blank=False)
    start_date=models.DateField(blank=False)
    departure_date=models.DateField(blank=False)
    is_active=models.BooleanField(default=False)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Formación académica"
        ordering = ["id"]

    def __str__(self):
        return self.educational_level


class IdiomasModel(models.Model):
    
    language_list=(
        ("Nativo", "Nativo"),
        ("Principiante", "Principiante"),
        ("Intermedio", "Intermedio"),
        ("Avanzado", "Avanzado"),
    )
    id=models.AutoField(primary_key=True)
    language=models.CharField(max_length=25, blank=False)
    level=models.CharField(choices=language_list, max_length=13, blank=False)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Idioma"
        verbose_name_plural = "Idiomas"
        ordering = ["language"]

    def __str__(self):
        return self.language


class CursosCertificacionesModel(models.Model):
    
    id=models.AutoField(primary_key=True)
    course=models.CharField(max_length=50,blank=False )
    college=models.CharField(max_length=50,blank=True, null=True )
    link=models.URLField(max_length=70,blank=True, null=True)
    start_date=models.DateField(blank=True, null=True)
    departure_date=models.DateField(blank=True, null=True)
    is_active=models.BooleanField(default=False)
    description=models.TextField(max_length=50)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
        ordering = ["course"]

    def __str__(self):
        return self.course

class CvFileModel(models.Model):
    
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50, blank=False)
    file=models.FileField(upload_to="file/%y/%m/%d/")
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)


    class Meta:
        verbose_name = "Archivo"

    def __str__(self):
        return self.name

dashboard/forms.py
from django import forms
from django.forms.widgets import Input, Textarea
from django.utils.translation import gettext_lazy as _
from .models import (DatosPersonalesModel, DatosContactoModel, ExperienciaProfesionalModel, ObjetivoProfesionalModel,
                     FormacionAcademicaModel, IdiomasModel, CursosCertificacionesModel,   
                      CvFileModel )

class DatosPersonalesForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DatosPersonalesForm, self).__init__(*args, **kwargs)
        self.fields['other'].widget.attrs['class']='form-control'
        self.fields['other'].widget.attrs['placeholder']='Máx 200 caracteres'
    

    class Meta:
        model=DatosPersonalesModel
        fields="__all__"
        exclude=['user']
        
        labels={
            'date_of_birth':"Fecha de nacimiento",
            'image':"Foto de perfil",
            'sex':"Genero",
            'relocate':"Disponibilidad para reubicarse",
            'country':"País",
            'zip_code':"Código postal",
            'state':"Estado",
            'city':"Ciudad",
            'town':"Alcadía o municipio",
            'other':_("Información adicional")
        }
        
        widgets = {
            'date_of_birth': Input(
                attrs={
                    'type':'date',
                    "required":True
                }
            )
        }

        error_messages = {
            'zip_code': {
                'max_length': ("La longitud no debe superar los 10"),
            
            },
        }



class DatosContactoForm(forms.ModelForm):

    class Meta:
        model=DatosContactoModel
        fields="__all__"
        exclude=['user']
        labels={
            'telephone':"Teléfono",
            'cellphone':"Celular",
            'facebook_social_url':"Facebook",
            'twitter_social_url':"Twitter",
            'instragram_socila_url':"Instagram",
        }
    
class ObjetivoProfesionalForm(forms.ModelForm):
    
    class Meta:
        model=ObjetivoProfesionalModel
        fields="__all__"
        exclude=['user']
        labels={
            'employment':"Puesto deseado",
            'salary':"Sueldo deseado",
            'objective':"Objetivos profesionales",
        }
    
        widgets = {
            'objective': Textarea(
                attrs={
                    'class':'form-control',
                    "placeholder":"Máximo 200 caracteres"
                }
            )
        }


class ExperienciaProfesionalForm(forms.ModelForm):

    class Meta:
        model=ExperienciaProfesionalModel
        fields="__all__"
        exclude=['user']

        labels={
            'employment':"Posición laboral",
            'company':"Empresa",
            'activities':"Actividades y funciones",
            'start_date':"Fecha de inicio",
            'departure_date':"Fecha de finalización",
            'is_active':"Sigo trabajando",
        }

        widgets = {
            'start_date': Input(attrs={'type':'date'}),
            'departure_date': Input(attrs={'type':'date'}),
            'activities': Textarea (
                attrs={
                    'class':'form-control',
                    "placeholder":"Máximo 200 caracteres"
                }
            )
        }


class FormacionAcademicaForm(forms.ModelForm):

    class Meta:
        model=FormacionAcademicaModel
        fields="__all__"
        exclude=['user']
        labels={
            'education_level':"Grado de estudio",
            'college':"Nombre de la institución",
            'career':"Carrera",
            'start_date':"Fecha de inicio",
            'departure_date':"Fecha de finalización",
            'is_active':"Sigo estudiando",
        }

        widgets = {
            'start_date': Input(attrs={'type':'date'}),
            'departure_date': Input(attrs={'type':'date'})
        }

class IdiomasForm(forms.ModelForm):

    class Meta:
        model=IdiomasModel
        fields="__all__"
        exclude=['user']
        labels={
            'language':"Idioma",
            'level':"Nivel",
        }


class CursosCertificacionesForm(forms.ModelForm):

    class Meta:
        model=CursosCertificacionesModel
        fields="__all__"
        exclude=['user']
        labels={
            'course':"Curso o certificación",
            'link':"Enlace",
            'start_date': "Fecha de inicio",
            'departure_date': "Fecha de finalización",
            'is_active':"Sigo estudiando",
            'description':"Descripción",
        }

        widgets = {
            'start_date': Input(attrs={'type':'date'}),
            'departure_date': Input(attrs={'type':'date'})
        }

class CvFileForm(forms.ModelForm):

    class Meta:
        model=CvFileModel
        fields=['name', "file", "user"]
        labels={
            'name':"Nombre",
            'file':"Adjuntar",
        }

        

templates/dashboard/objetivo_profesional/create.html
{% extends "dashboard/index.html" %}
{% load static %}
{% block right-content %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h2>Objetivos Profesionales</h2>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Crear Objetivo</strong>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">{% csrf_token %}
                            <p><label for="id_employment">Puesto deseado:</label> <input type="text" name="employment" maxlength="50" required id="id_employment"></p>
                            <p><label for="id_salary">Sueldo deseado:</label> <input type="number" name="salary" step="any" required id="id_salary"></p>
                            <p><label for="id_divisa">Divisa:</label> 
                                <select name="divisa" id="id_divisa">
                                <option value="" selected>---------</option>
                                <option value="MX">MX</option>
                                <option value="USD">USD</option>
                              </select></p>
                            <p><label for="id_objective">Objetivos profesionales:</label> 
                            <textarea name="objective" cols="40" rows="10" maxlength="2000" id="id_objective">
                            </textarea></p>
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </form>
                    </div>
              </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}

templates/dashboard/objetivo_profesional/template.html
{% extends "dashboard/index.html" %}
{% load static %}
{% block right-content %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h2>Objetivos Profesionales</h2>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">
        <div class="row">            
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        {% for data in data_user %}
                        <p>Puesto solicitado: {{data.employment}}</p>
                        <p>Sueldo deseado: {{data.salary}}</p>
                        <p>Divisa: {{data.divisa}}</p>
                        <p>Objetivo: {{data.objective}}</p>
                        <a href="{% url 'objetivos_modificacion' data.id %}" class="btn btn-danger">Actualizar  informacion</a>
                        {% endfor %}
                        <a href="{% url 'experiencia_profesional' %}" class="btn btn-success">Ir a Experiencia Profesional</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}

templates/dashboard/objetivo_profesional/update.html
{% extends "dashboard/index.html" %}
{% load static %}
{% block right-content %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h2>Objetivos profesionales</h2>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Actualizacion Objetivos</strong>
                    </div>
                    <div class="card-body">
                        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </form>
                    </div>
              </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}