app/support/urls.py
from django.urls import path
from .views import (FAQView, FAQListView, AssistanceView, AssistanceCreateView,AssistanceListView, 
                    AssistanceUpdateView, FeedbackView)

app_name="support"

urlpatterns = [
    
    path('faq/', FAQView.as_view(), name="faq"),
    path('faq_list/', FAQListView.as_view(), name="faq_list"),
    path('assistance/', AssistanceView.as_view(), name="assistance"),
    path('assistance_list/', AssistanceListView.as_view(), name="assistance_list"),
    path('assistance_create/', AssistanceCreateView.as_view(), name="assistance_create"),
    path('assistance_update/<int:pk>', AssistanceUpdateView.as_view(), name="assistance_update"),
    path('feedback/', FeedbackView.as_view(), name="feedback"),#AJAX
    
    ]

curriculo/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from home.views import Error404View, Error500View


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('account.urls')),
    path('profile/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('support/', include('app.support.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    
handler404 = Error404View.as_view()
handler500 = Error500View.as_error_view()

dashboard/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import( DashboardView, DatosPersonalesCreateView, DatosPersonalesView, DatosPersonalesUpdateView, 
                    DatosContactoView,DatosContactoCreateView, DatosContactoUpdateView, ExperienciaProfesionalView,
                    ExperienciaProfesionalUpdateView,ExperienciaProfesionalCreateView,ExperienciaProfesionaDeleteView, 
                    ObjetivosView, ObjetivosCreateView, ObjetivosUpdateView, FormacionAcademicaView, 
                    FormacionAcademicaCreateView, FormacionAcademicaUpdateView, FormacionAcademicaDeleteView,
                    IdiomasView, IdiomasCreateView, IdiomasUpdateView, IdiomasDeleteView,CursosView, CursosCreateView,
                    CursosUpdateView, CursosDeleteView, CvFileView )


urlpatterns = [
    path('', login_required(DashboardView.as_view()), name="dashboard"),
    path('datos_personales/', login_required(DatosPersonalesView.as_view()), name="datos_personales"),
    path('datos_personales_agregar/',login_required(DatosPersonalesCreateView.as_view()), 
                                                name="datos_personales_agregar"),
    path('datos_personales_modificacion/<int:pk>', login_required(DatosPersonalesUpdateView.as_view()), 
                                                name="datos_personales_modificacion"),
    path('datos_contacto/',login_required(DatosContactoView.as_view()), name="datos_contacto"),
    path('datos_contacto_agregar/', login_required(DatosContactoCreateView.as_view()), name="datos_contacto_agregar"),
    path('datos_contacto_modificacion/<int:pk>', login_required(DatosContactoUpdateView.as_view()), 
                                                name="datos_contacto_modificacion"),
    path('objetivos/', login_required(ObjetivosView.as_view()), name="objetivos"),
    path('objetivos_agregar/', login_required(ObjetivosCreateView.as_view()), name="objetivos_agregar"),
    path('objetivos_modificacion/<int:pk>', login_required(ObjetivosUpdateView.as_view()), 
                                                name="objetivos_modificacion"),
    path('experiencia_profesional/', login_required(ExperienciaProfesionalView.as_view()), 
                                                name="experiencia_profesional"),
    path('experiencia_profesional_modificacion/<int:pk>', login_required(ExperienciaProfesionalUpdateView.as_view()), 
                                                name="experiencia_profesional_modificacion"),
    path('experiencia_profesional_agregar/', login_required(ExperienciaProfesionalCreateView.as_view()), 
                                                name="experiencia_profesional_agregar"),    
    path('experiencia_profesional_eliminar/<int:pk>', login_required(ExperienciaProfesionaDeleteView.as_view()), 
                                                name="experiencia_profesional_eliminar"),                                                
    path('formacion_academica/', login_required(FormacionAcademicaView.as_view()), name="formacion_academica"),
    path('formacion_academica_modificacion/<int:pk>', login_required(FormacionAcademicaUpdateView.as_view()), 
                                                name="formacion_academica_modificacion"),
    path('formacion_academica_agregar/',login_required(FormacionAcademicaCreateView.as_view()), 
                                                name="formacion_academica_agregar"),    
    path('formacion_academica_eliminar/<int:pk>', login_required(FormacionAcademicaDeleteView.as_view()), 
                                                name="formacion_academica_eliminar"),                                                                                        
    path('idiomas/', login_required(IdiomasView.as_view()), name="idiomas"),
    path('idiomas_modificacion/<int:pk>', login_required(IdiomasUpdateView.as_view()), name="idiomas_modificacion"),
    path('idiomas_agregar/', login_required(IdiomasCreateView.as_view()), name="idiomas_agregar"),    
    path('idiomas_eliminar/<int:pk>', login_required(IdiomasDeleteView.as_view()), name="idiomas_eliminar"),
    path('cursos/',login_required(CursosView.as_view()), name="cursos"),
    path('cursos_modificacion/<int:pk>', login_required(CursosUpdateView.as_view()), name="cursos_modificacion"),
    path('cursos_agregar/', login_required(CursosCreateView.as_view()), name="cursos_agregar"),    
    path('cursos_eliminar/<int:pk>', login_required(CursosDeleteView.as_view()), name="cursos_eliminar"),
    path('cv', login_required(CvFileView.as_view()), name="cv"),
]

home/urls.py
from django.urls import path
from .views import HomeView

app_name="home"


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    
    ]

dashboard/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View
from profile.permissions import cvFilePermission
from profile.mixins import CvFilePermissionMixin
from dashboard.forms import (DatosPersonalesForm, DatosContactoForm, ExperienciaProfesionalForm, 
                    ObjetivoProfesionalForm,FormacionAcademicaForm, IdiomasForm, CursosCertificacionesForm, CvFileForm)
from dashboard.models import (DatosPersonalesModel, DatosContactoModel, ExperienciaProfesionalModel, ObjetivoProfesionalModel,
                     FormacionAcademicaModel, IdiomasModel, CursosCertificacionesModel,CvFileModel )


class DashboardView(TemplateView):
    """Main Dashboard
        
        
        :TemplateView: django view
    """
    model=DatosPersonalesModel
    template_name="dashboard/dashboard.html"

    def get(self, request, *args, **kwargs):
        
        try:
            data_user=self.model.objects.get(user=request.user)
            image=data_user.image
            
        except:
            
            image=False
        
        return render(request, self.template_name, {"image":image})
    

class DatosPersonalesView(TemplateView):
    "User data"

    model=DatosPersonalesModel
    template_name="dashboard/datos_personales/template.html"
    
    def get(self, request, *args, **kwargs):
        
        data_user=self.model.objects.filter(user=request.user)
        
        if data_user:
          
            return render(request, self.template_name, {"data_user":data_user})
        else:
          
            return redirect("datos_personales_agregar")

class DatosPersonalesCreateView(CreateView):
    """User data
        
        
        :CreateView: django view allows create user
    """

    model=DatosPersonalesModel
    form_class=DatosPersonalesForm
    template_name='dashboard/datos_personales/create.html'
    context_object_name="form"
    success_url=reverse_lazy("datos_personales")

    def form_valid(self, form):
        "get user"
        
        form.instance.user = self.request.user
        
        return super().form_valid(form)


class DatosPersonalesUpdateView(UpdateView):
    """Update user data
        
        
        :UpdateView:django view
    """

    model=DatosPersonalesModel
    form_class=DatosPersonalesForm
    template_name="dashboard/datos_personales/update.html"
    context_object_name="form"
    success_url=reverse_lazy("datos_personales")


class DatosContactoView(View):
    """User data
        
        
        :View:django view
    """
    model=DatosContactoModel
    template_name="dashboard/datos_contacto/template.html"
    
    def get(self, request, *args, **kwargs):
      
        data_user=self.model.objects.filter(user=request.user)
        
        if data_user:
            
            return render(request, self.template_name, {"data_user":data_user})
        else:
          
            return redirect("datos_contacto_agregar")

class DatosContactoCreateView(CreateView):
    
    model=DatosContactoModel
    form_class=DatosContactoForm
    template_name='dashboard/datos_contacto/create.html'
    context_object_name="form"
    success_url=reverse_lazy("datos_contacto")

    def form_valid(self, form):
        "get user"
        
        form.instance.user = self.request.user
        return super().form_valid(form)


class DatosContactoUpdateView(UpdateView):
    "Update data"

    model=DatosContactoModel
    form_class=DatosContactoForm
    template_name="dashboard/datos_contacto/update.html"
    context_object_name="form"
    success_url=reverse_lazy("datos_contacto")


class ObjetivosView(View):
    
    model=ObjetivoProfesionalModel
    template_name="dashboard/objetivo_profesional/template.html"
    
    def get(self, request, *args, **kwargs):
        
        data_user=self.model.objects.filter(user=request.user)
        if data_user:
          
            return render(request, self.template_name, {"data_user":data_user})
        else:
          
            return redirect("objetivos_agregar")


class ObjetivosCreateView(TemplateView):
    "Create data"

    model=ObjetivoProfesionalModel
    template_name='dashboard/objetivo_profesional/create.html'
    success_url=reverse_lazy("objetivos")

    def post(self, request, *args, **kwargs):
        "get data user"
        
        employment=request.POST.get("employment")
        salary=request.POST.get("salary")
        divisa=request.POST.get("divisa")
        objective=request.POST.get("objective")
        objetivoProfesional1=self.model(employment=employment, salary=salary, divisa=divisa, 
                                objective=objective,user=request.user)                        
        objetivoProfesional1.save()
        
        # Set permissions
        cvFilePermission(request.user, CvFileModel)
        
        return HttpResponseRedirect(self.success_url)


class ObjetivosUpdateView(UpdateView):
    

    model=ObjetivoProfesionalModel
    form_class=ObjetivoProfesionalForm
    template_name="dashboard/objetivo_profesional/update.html"
    context_object_name="form"
    success_url=reverse_lazy("objetivos")


class ExperienciaProfesionalView(TemplateView):
    

    model=ExperienciaProfesionalModel
    template_name="dashboard/experiencia_profesional/template.html"
    
    def get(self, request, *args, **kwargs):
        
        data_user=self.model.objects.filter(user=request.user)
        data_user=data_user.order_by("-is_active", "-start_date")# - DES
       
        if data_user:
          
            return render(request, self.template_name, {"data_user":data_user})
        else:
          
            return redirect("experiencia_profesional_agregar")
            

class ExperienciaProfesionalUpdateView(UpdateView):
    "Update data"

    model=ExperienciaProfesionalModel
    form_class=ExperienciaProfesionalForm
    template_name="dashboard/experiencia_profesional/update.html"
    context_object_name="form"
    success_url=reverse_lazy("experiencia_profesional")

class ExperienciaProfesionalCreateView(CreateView):
    "create data"

    model=ExperienciaProfesionalModel
    form_class=ExperienciaProfesionalForm
    template_name='dashboard/experiencia_profesional/create.html'
    context_object_name="form"
    success_url=reverse_lazy("experiencia_profesional")

    def form_valid(self, form):
        "get user"
        
        form.instance.user = self.request.user
        
        return super().form_valid(form)

class ExperienciaProfesionaDeleteView(DeleteView):
    "delete data"
    
    model=ExperienciaProfesionalModel
    context_object_name="form"
    template_name='dashboard/experiencia_profesional/delete.html'
    success_url=reverse_lazy("experiencia_profesional")


class FormacionAcademicaView(View):
   

    model=FormacionAcademicaModel
    template_name="dashboard/formacion_academica/template.html"
    
    def get(self, request, *args, **kwargs):
        
        data_user=self.model.objects.filter(user=request.user)
        if data_user:
          
            return render(request, self.template_name, {"data_user":data_user})
          
        else:
          
            return redirect("formacion_academica_agregar")
            

class FormacionAcademicaUpdateView(UpdateView):
   

    model=FormacionAcademicaModel
    form_class=FormacionAcademicaForm
    template_name="dashboard/formacion_academica/create.html"
    context_object_name="form"
    success_url=reverse_lazy("formacion_academica")

class FormacionAcademicaCreateView(CreateView):
    

    model=FormacionAcademicaModel
    form_class=FormacionAcademicaForm
    template_name='dashboard/formacion_academica/create.html'
    context_object_name="form"
    success_url=reverse_lazy("formacion_academica")

    def form_valid(self, form):
      
        form.instance.user = self.request.user
        return super().form_valid(form)

class FormacionAcademicaDeleteView(DeleteView):
    

    model=FormacionAcademicaModel
    context_object_name="form"
    template_name='dashboard/formacion_academica/delete.html'
    success_url=reverse_lazy("formacion_academica")

class IdiomasView(View):
    
    model=IdiomasModel
    template_name="dashboard/idiomas/template.html"
    
    def get(self, request, *args, **kwargs):
        
        data_user=self.model.objects.filter(user=request.user)
        
        if data_user:
          
            return render(request, self.template_name, {"data_user":data_user})
        else:
          
            return redirect("idiomas_agregar")
            

class IdiomasUpdateView(UpdateView):
    

    model=IdiomasModel
    form_class=IdiomasForm
    template_name="dashboard/idiomas/create.html"
    context_object_name="form"
    success_url=reverse_lazy("idiomas")

class IdiomasCreateView(CreateView):
    

    model=IdiomasModel
    form_class=IdiomasForm
    template_name='dashboard/idiomas/create.html'
    context_object_name="form"
    success_url=reverse_lazy("idiomas")

    def form_valid(self, form):
        
        form.instance.user = self.request.user
        return super().form_valid(form)

class IdiomasDeleteView(DeleteView):

    model=IdiomasModel
    context_object_name="form"
    template_name='dashboard/idiomas/delete.html'
    success_url=reverse_lazy("idiomas")

class CursosView(View):
    

    model=CursosCertificacionesModel
    template_name="dashboard/cursos/template.html"
    
    def get(self, request, *args, **kwargs):
        data_user=self.model.objects.filter(user=request.user)
        if data_user:
            return render(request, self.template_name, {"data_user":data_user})
        else:
            return redirect("cursos_agregar")
            

class CursosUpdateView(UpdateView):
    

templates/dashboard/dashboard.html
{% extends "dashboard/index.html" %}
{% load static %}
{% block right-content %}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-12">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h2>Mi Dashboard</h2>
                    </div>
                </div>        
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body" style="text-align: center;">
                        <h1>Bienvenido {{user.username}} ¡Ahora puede crear su curriculum! </h1>
                        <a href="{% url 'datos_personales' %}">En la barra derecha 
                            encontrará diferentes opciones
                        </a>
                        <img src="{% static 'dashboard/ima/welcome1.svg' %}" alt="">
                    </div>
                </div>          
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}

templates/dashboard/index.html
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Curriculo.page</title>{% load static %}
    <meta name="description" content="crear curriculum, hoja de vida, curriulum vitae">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">    
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'account/images/favicon.png' %}">
    <link rel="shortcut icon" href="{% static 'account/images/favicon1.png'%}">
    <link rel="stylesheet" href="{% static 'account/assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'account/assets/css/style.css' %}">
    {% block style %}
    {% endblock style %}
</head>
<body>
    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-title">Mis datos</li><!-- /.menu-title -->         
                    <li class="menu-item-has-children dropdown"> 
                        <a href="{% url 'datos_personales' %}" class="dropdown-toggle" ><i class="menu-icon fa fa-user"></i>Personales</a>
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'datos_contacto' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-id-card"></i>Contacto</a>    
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'objetivos' %}" class="dropdown-toggle"  aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-object-group"></i>Objetivos</a>
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'experiencia_profesional' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-user-o"></i>Experiencia</a>
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'formacion_academica' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-user-md"></i>Estudios</a>    
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'idiomas' %}" class="dropdown-toggle"  aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-language"></i>Idiomas</a>
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'cursos' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-certificate"></i>Cursos</a>
                    </li>
                    <li class="menu-item-has-children dropdown">   
                        <a href="{% url 'cv' %}" class="dropdown-toggle"  aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Cv Archivo</a>
                    </li>
                    <li class="menu-title">Mi cuenta</li><!-- /.menu-title -->
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-vcard"></i>Mi cuenta</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="menu-icon fa fa-info"></i><a href="{% url 'account' %}">Datos de cuenta</a></li>
                            <li><i class="menu-icon fa fa-chain"></i><a href="{% url 'change' %}">Cambiar contraseña</a></li>
                            <li><i class="menu-icon fa fa-warning"></i><a href="{% url 'delete_user' user.id %}">Eliminar cuenta</a></li>
                            <li><i class="menu-icon fa fa-close"></i><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="./"><img src="{% static 'account/images/logo.png' %}" alt="Logo"></a>
                    <a class="navbar-brand hidden" href="./"><img src="{% static 'account/images/logo1.png' %}" alt="Logo"></a>
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
                    <div class="header-left">
                        <div class="dropdown for-notification">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-money"></i> <!-- <i class="fa fa-bell"></i> -->
                                <span class="count bg-danger">3</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="notification">
                                <p class="red">¿Desea donar?</p>
                                <a class="dropdown-item media" href="#">
                                    <i class="fa fa-check"></i>
                                    <p>PayPal</p>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <i class="fa fa-info"></i>
                                    <p>Notificación #2.</p>
                                </a>
                                <a class="dropdown-item media" href="#">
                                    <i class="fa fa-warning"></i>
                                    <p>Notificación #3.</p>
                                </a>
                            </div>
                        </div>
                        <div class="dropdown for-message">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-question-circle"></i>
                                <span class="count bg-primary">3</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="message">
                                <p class="red">Soporte y Ayuda</p>
                                <a class="dropdown-item media" href="{% url 'support:faq' %}">
                                    <div class="message media-body">
                                        <span class="name float-left">Preguntas Frecuentes</span>
                                        <span class="time float-right">Sugerencia</span>
                                        <p>¿No sabe por donde empezar?</p>
                                    </div>
                                </a>
                                <a class="dropdown-item media" href="{% url 'support:assistance' %}">
                                    <div class="message media-body">
                                        <span class="name float-left">Diseño personalizado</span>
                                        <span class="time float-right">Asesoría</span>
                                        <p>¿Necesita un diseño personalizado?</p>
                                    </div>
                                </a>
                                
                                <a class="dropdown-item media" href="{% url 'support:feedback' %}">
                                    <div class="message media-body">
                                        <span class="name float-left">Comentarios</span>
                                        <span class="time float-right">Observaciones</span>
                                        <p>¿Desea dejarnos algunas observaciones?</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">  
                            {% if image %}
                                <img class="user-avatar rounded-circle" src="{{image.url}}" alt="User Avatar">
                            {% else %}
                            <i class="menu-icon fa fa-user-circle"></i>
                            {% endif %}
                        </a>
                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="{% url 'perfil' %}" target="_blank"><i class="fa fa- user"></i>Mi curriculum</a>
                            <a class="nav-link" href="#"><i class="fa fa- user"></i>Notificaciones <span class="count">13</span></a>
                            <a class="nav-link" href="{% url 'account' %}"><i class="fa fa -cog"></i>Mi cuenta</a>
                            <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-power -off"></i>Salir</a>
                        </div>
                    </div>

                </div>
            </div>
        </header>
        <!-- /#header -->
        <!--rigth content -->
        {% block right-content %}
        {% endblock %}
        <!-- Footer -->
        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2021 curriculo.page
                    </div>
                    <div class="col-sm-6 text-right">
                        Powered by <a href="https://webfomatica.com">webfomatica</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /.site-footer -->
    <!-- /#right-panel -->
    </div>   
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <!-- static javascript -->
    <script src="{% static 'account/assets/js/main.js' %}"></script>
    <script>
        {% if messages %}
            let html_msg="";
            {% for msg in messages %}
                html_msg +='{{ msg }}';
            {% endfor %}
            alert(html_msg);
        {% endif %}
    </script>
    {% block scripts %}
    {% endblock scripts %}
    </body>
</html>